app:
  baseName: classpath:messages
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://${MYSQL_HOST:localhost}:3306/hotel
    username: root
    password: 123456
  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter:  pageSize
        one-indexed-parameters: true

